version: '3.9'

services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgSte
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Kafka + Zookeeper (confluent)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - backend

  # Log Service
  log-service:
    build:
      context: ./TaskManagementServiceLoging
      dockerfile: Dockerfile
    container_name: log-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseOptions__Host: postgres
      DatabaseOptions__Port: 5432
      DatabaseOptions__Name: log-service
      DatabaseOptions__User: postgres
      DatabaseOptions__Password: pgSte
      Kafka__BootstrapServers: kafka:9092
    ports:
      - "5258:80"
    depends_on:
      - postgres
      - kafka
    networks:
      - backend

  # Task Service
  task-service:
    build:
      context: ./TaskManagementService
      dockerfile: Dockerfile
    container_name: task-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseOptions__Host: postgres
      DatabaseOptions__Port: 5432
      DatabaseOptions__Name: task-service
      DatabaseOptions__User: postgres
      DatabaseOptions__Password: pgSte
      IdentityDatabaseOptions__Host: postgres
      IdentityDatabaseOptions__Port: 5432
      IdentityDatabaseOptions__Name: identity-db
      IdentityDatabaseOptions__User: postgres
      IdentityDatabaseOptions__Password: pgSte
      Kafka__BootstrapServers: kafka:9092
    ports:
      - "5250:80"
    depends_on:
      - postgres
      - kafka
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
